### ISSUE TITLE
Request: Critical injury permanency

### ISSUE THREAD

**Issue by rwisaak** [Perfectro/vaesen-foundry-vtt#2]
After completing a mystery, players must determine whether the Defects and Insights they have gained become permanent or wear off. Currently the system lacks a way to track if a listed injury has happened during the current mystery, or is a permanent carryover from a prior one.

Some way to signify that a particular critical injury has become permanent would be helpful.

**Comment by Perfectro** [comment]
I will look into it.

**Comment by Perfectro** [comment]
![image](https://user-images.githubusercontent.com/5683489/90291576-7ea2cc80-de80-11ea-92b8-cd490cab6d85.png)
Should do the trick for the moment.
Available on 1.4
