### ISSUE TITLE
Looking into supporting Vaesen for my blood-n-guts module

### ISSUE THREAD

**Issue by edzillion** [Perfectro/vaesen-foundry-vtt#4]
Hi

I am getting close to a production release of my module [blood-n-guts](https://github.com/edzillion/blood-n-guts) and I am looking into supporting systems other than 5e. Vaesen was suggested as a good option and I had a look at your system.

Unfortunately I am going to need some help setting up characters etc. Is there anyone here who is interested in helping out?

**Comment by Perfectro** [comment]
Hello.

I don't know why Vaesen was suggested. It's not a system with a lot of blood. Combat isn't the main aspect of the game. But hey, if people want blood, let give some blood to the blood god.

What do you need exactly ?

By the way, [Warhammer Fantasy Role Playing Game](https://foundryvtt.com/packages/wfrp4e/) is probably a better system to support for you. Critical injuries with lot of blood is part of the system. And there is way more player for it then Vaesen 😉

**Comment by edzillion** [comment]
Thanks @Perfectro I think that's a great suggestion, I am really only looking for a good non 5e system to try to adapt, as an exercise to see what is involved. 

wfrp4e is much more complete, and has a much bigger fanbase so I think it's a better target. Updating this issue now.

**Comment by Perfectro** [comment]
If you want to add Vaesen support and need some help, don't hesitate to reopen this issue.
